Extension { #name : #DateAndTime }

{ #category : #'*PostgresV2' }
DateAndTime >> julianDayNumber: anInteger [

	jdn := anInteger
]

{ #category : #'*PostgresV2' }
DateAndTime >> nanos: anInteger [

	nanos := anInteger
]

{ #category : #'*PostgresV2' }
DateAndTime >> offset: anInteger [

	offset := anInteger
]

{ #category : #'*PostgresV2' }
DateAndTime >> seconds: anInteger [

	seconds := anInteger
]
